### PR TITLE
Implement support for cut & paste

### PR DESCRIPTION
**Pull request by dbrgn**

### CODE REVIEW

**Comment by ovalseven8** [comment]
Hey @dbrgn!

Sorry, I don't want to interrupt you. I've just tested your demo page and sometimes I've problems with deleting content. Although all is selected, only the last character is deleted sometimes. Because issues are not open, I just wanted to let you know here.

peek 2019-02-27 10-32

**Comment by dbrgn** [comment]
Thanks for the note. Yes, this is WIP and will need more testing.

**Comment by dbrgn** [comment]
@ovalseven8 this will be fixed by #12.

**Comment by ovalseven8** [comment]
Cool, thanks! 👍 

One more issue. On Windows 10 (Firefox 65) it isn't displayed when emojis are selected:
abc

**Comment by ovalseven8** [comment]
Also <kbd>Ctrl</kbd>+<kbd>Z</kbd> for "Undo" would be important.

But sorry, I guess I should wait until it's not in "WIP" mode anymore. :smile:

**Comment by dbrgn** [comment]
Yes, please wait with reports until a first version is ready. Then I'll open the issue tracker :)

**Pull request merged**
